services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - 8080:8080
    container_name: jenkins_local
    volumes:
      - ./jenkins_data:/var/jenkins_home
    environment:
      - JENKINS_OPTS="" 