name: Reusable Test Workflow

on:
  workflow_call:
    inputs:
      test-type:
        required: true
        type: string
      browser:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Run Tests
        run: npx playwright test tests/${{ inputs.test-type }} --project=${{ inputs.browser }}